# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=20)),
                ('comment_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_sex', models.CharField(max_length=4)),
                ('driver_age', models.IntegerField(default=18)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Driver'),
        ),
    ]
