# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_blog_blogdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogabstract',
            field=models.TextField(default='aaaa'),
            preserve_default=False,
        ),
    ]
