# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_elictricdic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolingstationDic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coolingstation_item', models.CharField(max_length=120)),
            ],
        ),
    ]
