# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_coolingstationdic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coolingstationdic',
            old_name='Coolingstation_item',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='elictricdic',
            old_name='electric_item',
            new_name='menu_item',
        ),
    ]
