# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180522_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportdate',
            field=models.CharField(default='2018-05-22 11:05:30', max_length=120),
        ),
    ]
