# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180522_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reportpath',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reportdate',
            field=models.CharField(max_length=120),
        ),
    ]
